### ISSUE TITLE
Include tables and fig caption in a two layout column

### ISSUE THREAD

**Issue by nicocriscuolo** [grantmcdermott/two-col-test#1]
Hello and thanks a lot for this solution!

I would like to add both figure captions and tables (e. g. generated withe the`kable()` function of the **knitr** packge) inside a two-columns layout, but I keep getting errors:

- for figure caption, it seems that there's a problem with the "floating" aspect of the images;
- for the tables, I get the following error message: **Package longtable Error: longtable not in 1-column mode**.

Thanks!

p. s.: my markdown needs to be downloaded directly from a shiny app.

**Comment by grantmcdermott** [comment]
I haven't tried this for tables, but it seems to work well for figures:

1. Add the float package as a dependency for the pdf_document format.
```yaml
output:
  pdf_document:
    extra_dependencies: ["float"]
    <cont. with other options....>
```

2. Set the float position in the chunk as "H". You can either do globally with `knitr::opts_chunk$set(fig.pos = "H", out.extra = "")`, or specify it individually for each chunk.

Sources:
[a] https://tex.stackexchange.com/a/250368
[b] https://bookdown.org/yihui/rmarkdown-cookbook/figure-placement.html#prevent-figures-from-floating
