### ISSUE TITLE
Set different column width for the R markdown pdf output

### ISSUE THREAD

**Issue by nicocriscuolo** [grantmcdermott/two-col-test#2]
Hi,

based on the solution that you have proposed, is it possible to set a different width for each column when rendering a pdf document? I've noticed that this is possible for the HTML-output when you specify the width inside the **css** file, but I am wondering if something similar can be achieved also to produce the pdf.

Thanks

**Comment by grantmcdermott** [comment]
Hi @nicocriscuolo,

Sorry for the embarrassingly slow reply. The answer is "yes!" thanks to a better approach for specifying the columns with Pandoc's fenced_div method. 

I've updated my repo, so you might as well as pull to get the changes. In the .Rmd file, you'll see the fenced divs is where we specify the column width (e.g. [here](https://github.com/grantmcdermott/two-col-test/blob/master/two-col-test.Rmd#L24)).
